language: python

python:
  - "2.7"
  - "3.3"

install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements/base.txt; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r requirements/py3.txt; fi"

script:
  - "./run_tests.sh dsfp.tests"
